### PR TITLE
Cleanup deprecated handler

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

We've already deprecate those handlers and send requests directly for kube-apiserver.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/label tide/merge-method-squash

### CODE REVIEW

**Comment by 196Ikuchil** [comment]
@sanposhiho 
These changes LGTM.

Btw, should this section also be removed?
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/docs/api.md?plain=1#L104-L537

**Comment by sanposhiho** [comment]
> Btw, should this section also be removed?

Ah yes, you are right. I'll remove them

**Comment by sanposhiho** [comment]
@196Ikuchil updated/

**Comment by 196Ikuchil** [comment]
Thank you.
I have confirmed that the resources can be operated normally from the frontend.
/lgtm

**Pull request merged**
