### PR TITLE
Fix error handling on calling of reset function on the web UI.

### LINKED ISSUE #151: [Frontend] `Reset` returns a success message even if it fails
When we click a `RESET` button, it  returns a success message even if it fails
/kind bug

### PR DESCRIPTION
**Pull request by 196Ikuchil**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In the current logic, the `Reset` button returns a success message even if it fails, on the web UI.
Fixed that error handling logic.
#### Which issue(s) this PR fixes:

Fixes #151

#### Special notes for your reviewer:
Currently, the behavior check is not exactly finished.
So, this PR should be merged after #162.

/label tide/merge-method-squash
/hold

### CODE REVIEW

**Comment by 196Ikuchil** [comment]
/retitle Fix error handling on calling of reset function on the web UI.

**Review by sanposhiho — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
