### PR TITLE
Remove no longer needed resource service

### LINKED ISSUE #139: Deprecate internal Service for each resource (NodeService, PodService... etc)
WebUI doesn't use handlers and we deprecated handlers.
Services for each resource are created to implement the some specific logic to manage resources in the simulator. 
For example, we need to use `GracePeriodSeconds` in the simulator when delete pods, because there are no actual Pods running in the simulator.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/541a021f8b98eb1ae102ec823fad721a91afd36e/pod/pod.go#L85

I expected to see more of this kinda simulator-specific logic in the future as the simulator grew larger, but actually that didn't happen.
I'd propose to remove services for each resource and use kubernetes client directly from all other services.

/priority important-long-term
/kind cleanup

### PR DESCRIPTION
**Pull request by 196Ikuchil**
#### What type of PR is this?
/area simulator
/kind cleanup

#### What this PR does / why we need it:
We no longer need each resource service.

#### Which issue(s) this PR fixes:

closes #139 #233

#### Special notes for your reviewer:

/label tide/merge-method-squash

### CODE REVIEW

**Comment by sanposhiho** [comment]
@196Ikuchil Sorry about the delay, FYI https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/304 is merged

**Comment by 196Ikuchil** [comment]
Thanks! 
Please review this? 🙏 

/assign @sanposhiho

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
