### PR TITLE
Added APIExtensionServer and AggregatorServer into the simulator to accept CRDs

### PR DESCRIPTION
**Pull request by matthewygf**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR tries to extend the simulator apiserver to accept CRDs, this is useful because some scheduler-plugins uses CRDs. #77 

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:

After this extension, user can use kubectl to apply CRDs.

/label tide/merge-method-squash

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
Hi @matthewygf. Thanks for your effort. 
Your changes are looks valid. I've tried your branch and confirmed that it works correctly.
But as you said in [the comment](https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/77#issuecomment-1040586669), most of the logic on this PR is duplicated with [the starting point of kube-apiserver in k/k](https://github.com/kubernetes/kubernetes/blob/30a21e9abdbbeb78d2b7ce59a79e46299ced2742/cmd/kube-apiserver/app/server.go#L169). 
This project is owned by sig/scheduling, and we (at least I) may not be aware of the big changes in kube-apiserver in k/k. Therefore, I am a little concerned about managing the complicated logic of kube-apiserver here and would like to use the functionality provided by k/k as is if possible. This allows us to focus more on the logic for the simulations and less on managing the logic of the kube-apiserver ourselves.

So, I hope we can replace whole our kube-apiserver starting point with [CreateServerChain func in k/k](https://github.com/kubernetes/kubernetes/blob/30a21e9abdbbeb78d2b7ce59a79e46299ced2742/cmd/kube-apiserver/app/server.go#L169) instead of creating the copy of the logic in CreateServerChain if we can.

WDYT? 
(Please note that this is not asking you to make any such changes on this PR. This project is entirely volunteer, including myself, and no one can force anyone else to do the work :)
If we decide here to use CreateServerChain in k/k instead of this PR, that will be done by someone(may include you) who is interested.)

**Comment by matthewygf** [comment]
Hi @sanposhiho 

Thanks for the suggestion, I think that is the right approach, that way we can just focus on the scheduling code.

I am happy to work on it too :)

**Comment by sanposhiho** [comment]
@matthewygf 
Thanks. Yeah, feel free to close this.

**Comment by matthewygf** [comment]
closing as discussed

**Comment by matthewygf** [comment]
Hi @sanposhiho , unfortunately , I don't think this is as straightforward as I thought :/ , do you have any suggestions on getting this feature in ? 

The reasons are:  
1. CreateServerChain method only allows you to pass in a "completedOptions" , which does not allow us to specify the "controlplaneconfig.genericConfig.Authentication.Authenticator and LoopBackClientConfig", see our existing k8sapiserver lines[150](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ca3dc0dcb4ffabcca46406886e7021b85f03c870/k8sapiserver/k8sapiserver.go#L150) to lines[172](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ca3dc0dcb4ffabcca46406886e7021b85f03c870/k8sapiserver/k8sapiserver.go#L172)
2. The methods for "createAPIExtensionsConfig/Server" and "createAggregatorConfig/Server" are not exported, which makes this even harder to reuse some of the logic...


any suggestions would be appreciated...

**Comment by sanposhiho** [comment]
Thanks for investigating @matthewygf!

> 1. CreateServerChain method only allows you to pass in a "completedOptions" , which does not allow us to specify the "controlplaneconfig.genericConfig.Authentication.Authenticator and LoopBackClientConfig", see our existing k8sapiserver lines[150](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ca3dc0dcb4ffabcca46406886e7021b85f03c870/k8sapiserver/k8sapiserver.go#L150) to lines[172](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ca3dc0dcb4ffabcca46406886e7021b85f03c870/k8sapiserver/k8sapiserver.go#L172)

How about using [SecureServing](https://github.com/kubernetes/kubernetes/blob/5b1e5387591dd3ad0b3ddacc9e44a6ac7260078e/cmd/kube-apiserver/app/options/options.go#L45) in completedServerRunOptions(ServerRunOptions)?
I took a quick look at the implementation of kubernetes and found that LoopbackClientConfig is configured with SecureServing [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L364].
Sorry if you have already tried this.

**Comment by matthewygf** [comment]
@sanposhiho Thanks for the quick reply and no need to say sorry!  

Will get back to you on this, the [authenticator settings](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ca3dc0dcb4ffabcca46406886e7021b85f03c870/k8sapiserver/k8sapiserver.go#L163) were my next challenge :/ ...

_"(I am honestly not very knowledgeable about kube-apiserver entry point either, so could be wrong tho 😓)"_

Same haha, no problem at all , much appreciated for the help !

**Comment by sanposhiho** [comment]
@matthewygf 
> the [authenticator settings](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ca3dc0dcb4ffabcca46406886e7021b85f03c870/k8sapiserver/k8sapiserver.go#L163) were my next challenge :/ ...

Doesn't [`Authentication`](https://github.com/kubernetes/kubernetes/blob/5b1e5387591dd3ad0b3ddacc9e44a6ac7260078e/cmd/kube-apiserver/app/options/options.go#L49) in completedServerRunOptions(ServerRunOptions) work?
It looks like it is being used for GenericConfig.Authentication. (maybe, maybe...)
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L432

**Comment by matthewygf** [comment]
hi @sanposhiho , I have got an initial draft that works in another branch #121 , going to close this PR as it is not relevant , we can discuss in #121 .

Thanks for the help !

**Pull request closed without merging**
