### PR TITLE
Add k8s simple deploy manifest

### PR DESCRIPTION
**Pull request by 196Ikuchil**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
To achieve #133, the first step is to add a simple deploy manifest file.
- We can deploy the simulator(frontend/server) to the cluster using this file.
- Currently, it does not support the importing function of existing cluster resources.

##### How to use
```
$ kubectl apply -f recommended.yaml
$ kubectl port-forward svc/kube-scheduler-simulator-nginx 3000:3000 --namespace=kube-scheduler-simulator
```
Access to `http://localhost:3000/`.
#### Which issue(s) this PR fixes:

Relates #133

#### Special notes for your reviewer:
This PR is including the PR #153. 
Please review only this commit [96bd509](https://github.com/kubernetes-sigs/kube-scheduler-simulator/commit/96bd509e9396d37fc4008d0879fdeb21ab1f405d).
And we should merge PR #153 first.

/label tide/merge-method-squash

### CODE REVIEW

**Comment by sanposhiho** [comment]
> This PR is including the PR https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/153.
Please review only this commit [96bd509](https://github.com/kubernetes-sigs/kube-scheduler-simulator/commit/96bd509e9396d37fc4008d0879fdeb21ab1f405d).
And we should merge PR https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/153 first.

/hold

**Comment by 196Ikuchil** [comment]
I added the serviceaccount and supported the importing function by these commits. (But low-security considerations)

[6ad7207](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/154/commits/6ad7207343e625d4168107fb131838b39fbbfc0b)
[5983a1d](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/154/commits/5983a1d9c63b8a667b0bebe8a83adf8ef7394b5b)

**Comment by 196Ikuchil** [comment]
And until #84 is resolved, we are unable to verify correct behavior from Web UI.

**Pull request closed without merging**
