### PR TITLE
Bump Go 1.22

### PR DESCRIPTION
**Pull request by sivchari**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Bump Go1.22

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/label tide/merge-method-squash

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
/ok-to-test

**Comment by sivchari** [comment]
I've mentioned you [here](https://github.com/kubernetes/test-infra/pull/32324)

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
