### PR TITLE
Fix broken links and missing details in README

### PR DESCRIPTION
**Pull request by shahparth123**
#### What type of PR is this?
Fix to README documentation.

/area simulator
/kind documentation

#### What this PR does / why we need it:
It fix minor broken links in README.md file and also add namespace as Resource in documentation as it is added recently.
Fixes #
No additional feature/issue resolved in this PR. Only minor documentation fix added.

/label tide/merge-method-squash

### CODE REVIEW

**Comment by shahparth123** [comment]
> [CLA Missing ID](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/20677499/397377751/284/#/?version=2) [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/20677499/397377751/284/#/?version=2)
> 
> * ❌ The commit ([93ccae4](https://github.com/kubernetes-sigs/kube-scheduler-simulator/commit/93ccae4447d4ff1ef94346a4ad04f3784b4a868f)). This user is missing the User's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve.For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).


/easycla

**Review by sanposhiho — APPROVED** [review]
Great, thanks!

/approve
/lgtm

**Pull request merged**
