### PR TITLE
Fix lint frontend action to run for all changes under /web dir

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It's not working as expected now. We want this action to run for all changes under /web dir in pull requests.

#### Which issue(s) this PR fixes:

Ref #58

#### Special notes for your reviewer:

cc @sivchari 
/label tide/merge-method-squash

### CODE REVIEW

**Comment by sanposhiho** [comment]
Hm, it's not work with this change. I'll investigate.

**Comment by sanposhiho** [comment]
At least, it seems to work on master branch. 
https://github.com/kubernetes-sigs/kube-scheduler-simulator/actions/workflows/lint-frontend.yml

So, maybe, [the current change](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/72/commits/5f25dfaf2af2ca5199bf889070bf3f3b54258982) is not needed to resolve this issue. 😓

**Comment by sanposhiho** [comment]
I confirmed the frontend action works with this change.

https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/73

**Comment by sivchari** [comment]
@sanposhiho 

Thanks 👍

**Comment by sanposhiho** [comment]
This improvement will be not needed with #56. 
/close

**Pull request closed without merging**
