### PR TITLE
Update README.md to reflect the addition of PriorityClass

### PR DESCRIPTION
**Pull request by khalilswdp**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Updated the image on README.md to include PriorityClass, as well as added PriorityClass as a resource that we can simulate.

#### Which issue(s) this PR fixes:

This PR is related to #27

#### Special notes for your reviewer:

If there are other changes that I need to make, please tell me and I'll do them.

/label tide/merge-method-squash

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
Looks good. Please add priority class here as well.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/docs/how-it-works.md#1-users-request-creating-resource

**Comment by khalilswdp** [comment]
I have updated how-it-works

**Review by sanposhiho — APPROVED** [review]
Thanks for the great work @khalilswdp 
We finally complete supporting PritorityClass 🎉 

/lgtm
/approve

**Comment by khalilswdp** [comment]
Thank you @sanposhiho for helping me throughout my first ever contribution to the open source! This is one of the happiest days in my life!

**Pull request merged**
