### PR TITLE
Rename simulatorPlugin to wrappedPlugin

### LINKED ISSUE #124: rename simulator plugin to `wrappedplugin`
We will expand simulator plugin not only for simulator, but for other purposes. So, rename it to appropriate name.

https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/plugin/plugins.go#L238

### PR DESCRIPTION
**Pull request by 196Ikuchil**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Rename `simulatorPlugin` to `wrappedPlugin`.

#### Which issue(s) this PR fixes:

Fixes #124

#### Special notes for your reviewer:
Is this problem correctly fixed as you intended with this change?

/label tide/merge-method-squash
/assign @sanposhiho

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
Could you change [this](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/plugin/plugins.go#L248) to 
```
	pluginPrefix = "Wrapped"
```

**Comment by 196Ikuchil** [comment]
@sanposhiho Thanks!

**Review by sanposhiho — APPROVED** [review]
Thanks 👍 
/lgtm
/approve

**Pull request merged**
