### PR TITLE
Fix: file name .dockerignore has blank

### PR DESCRIPTION
**Pull request by sanposhiho**
Hello team.
.dockerignore has blank on its filename and git cannot checkout successfully on windows.

Thanks for reporting, @warmchang.

https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/8#issuecomment-908180585

### CODE REVIEW

**Comment by adtac** [comment]
The file is still empty? Did you mean to add a newline? I don't see it in the diff

**Comment by sanposhiho** [comment]
@adtac 
It looks like there is no change, but actually the file name has been changed :)

`.dockerignore  `  (two whitespaces after name) → `.dockerignore` (delete two whitespaces)

(You can tell from the URL that it contains two whitespaces (`%20%20`).)
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/.dockerignore%20%20

**Comment by sanposhiho** [comment]
@adtac ping

**Pull request merged**
