### PR TITLE
Bump etcd to v3.4.26

### LINKED ISSUE #308: Error response from daemon: application/vnd.docker.distribution.manifest.v1+prettyjws not supported
Following the "Getting Started" README and executing `make docker_build_and_up` on a fresh clone of master results in the error `Error response from daemon: application/vnd.docker.distribution.manifest.v1+prettyjws not supported`

M1 Macbook (MacOS 13.3.1)
Docker Desktop 4.20.1

### PR DESCRIPTION
**Pull request by des1redState**
Fixes #308

/area simulator
/kind bug
/label tide/merge-method-squash

### CODE REVIEW

**Comment by 196Ikuchil** [comment]
@des1redState 
Hi, Thank you for your PR!
Could you check [this comment](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/316#issuecomment-1666442998)?
I think that this PR looks good.

/ok-to-test

**Comment by 196Ikuchil** [comment]
Thanks @des1redState !
Sorry, there was one more point. Please check [this comment] and fix to commit message?

/retest

**Comment by sanposhiho** [comment]
@des1redState you need to change the commit as it suggested 
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/316#issuecomment-1666827057

**Comment by sanposhiho** [comment]
> ❌ The email address for the commit (https://github.com/kubernetes-sigs/kube-scheduler-simulator/commit/b4457633e6ef779c0e53cef973a2de7908d7e6c5) is not linked to the GitHub account, preventing the EasyCLA check.

Also please make sure you associate the correct email to your commit
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/316#issuecomment-1666442998

**Comment by 196Ikuchil** [comment]
@des1redState 
Thank you for your PR!

/approve

**Pull request merged**
