### PR TITLE
update(kubernetes): update kubernetes to v1.25.1

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/area simulator
/kind cleanup

#### What this PR does / why we need it:

- update kubernetes v1.25.1
- remove vendor and submodule because v1.25.1 has pkg/generated/openapi/zz_generated.openapi.go. (= we don't need to generate it anymore!)
  - also remove related script and Makefile

#### Which issue(s) this PR fixes:

For https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/46. 
CCv1 is introduced in v1.25.1.

#### Special notes for your reviewer:

/label tide/merge-method-squash

### CODE REVIEW

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/test-infra/pull/27563 will fix the test fail...

**Comment by 196Ikuchil** [comment]
I have verified that the simulator runs successfully.
Thank you!
/lgtm

**Pull request merged**
