### PR TITLE
Move PULL_REQUEST_TEMPLATE.md to a valid place

### PR DESCRIPTION
**Pull request by sanposhiho**
Hello. 
This PR just moves PULL_REQUEST_TEMPLATE.md to the valid place (under `.github/`).

### CODE REVIEW

**Comment by riita10069** [comment]
@sanposhiho 
Can I just LGTM this?

**Comment by sanposhiho** [comment]
@riita10069 

I think it requires reviewer permission. 🤔  

img

https://kubernetes.io/docs/contribute/review/for-approvers/

It is clear that this change will not have a negative impact. So, could you try `/lgtm`?
If you can, it's bug on prow, maybe. 🤔

**Comment by sanposhiho** [comment]
@riita10069 

Prow will label `lgtm` with it, but it seems that `/ltgm` from non-reviewers has no impact. 😢 

> /lgtm | Anyone, but triggers automation if a Reviewer or Approver uses it
https://kubernetes.io/docs/contribute/review/for-approvers/

**Comment by riita10069** [comment]
> Prow will label lgtm with it, but it seems that /ltgm from non-reviewers has no impact. 😢

Oh, yeah! I understand.

**Comment by riita10069** [comment]
Well, it merged!

**Comment by sanposhiho** [comment]
Hmmmmm, it's bug I think.

**Comment by sanposhiho** [comment]
I'll report it and check if it is expected behavior or not

**Comment by riita10069** [comment]
Thx!

**Comment by riita10069** [comment]
member can do `lgtm` label reference of following 
https://github.com/kubernetes/community/blob/master/community-membership.md#responsibilities-and-privileges

**Comment by sanposhiho** [comment]
Yes, but this doc says "Anyone, but triggers automation if a Reviewer or Approver". One of them is wrong.

> /lgtm | Anyone, but triggers automation if a Reviewer or Approver uses it
https://kubernetes.io/docs/contribute/review/for-approvers/

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/test-infra/issues/24660

**Comment by sanposhiho** [comment]
@riita10069 

Please don't add `/lgtm` on PRs from me until we can check if it is ok or not. (prow will merge it if a PR is from approver.)

**Pull request merged**
